
_ownership_state: established_at_birth
company_name: Software Company
company_slug: softwareco
enable_community_pack: false
enable_release_pack: false
enable_vouch_gate: false
l0_source_sha: b836a36b54558cb1e9c26f313c67bd2822cc13c4
l1_org_docs_profile: rich
l1_profile: custom
l2_org_docs_default: rich
maintainer_handle: '@template-owner'
repo_slug: softwareco

l1_ontology_layout: gitlink

