
_ownership_state: established_at_birth
company_name: Software Company
company_slug: softwareco
enable_community_pack: false
enable_release_pack: false
enable_vouch_gate: false
l0_source_sha: 33f286e116469590ae7d3b5c9150cc1cef3a903b
l1_org_docs_profile: rich
l1_profile: custom
l2_org_docs_default: rich
maintainer_handle: '@template-owner'
repo_slug: softwareco

